name: Docker

on: [push, pull_request]

jobs:
  Distros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [alpine, archlinux, centos, debian, fedora, opensuse, ubuntu]
      fail-fast: false
    env:
      DISTRO: ${{ matrix.distro }}
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=ci ${DISTRO}_env
    - name: Build devel project
      run: make --directory=ci ${DISTRO}_devel
    - name: Build project
      run: make --directory=ci ${DISTRO}_build
    - name: Test project
      run: make --directory=ci ${DISTRO}_test
    - name: Test Install project
      run: make --directory=ci ${DISTRO}_install_test
